### ISSUE TITLE
Corrupted model weight vsr_prelrs3vox2_base_ftlrs3.pth

### ISSUE THREAD

**Issue by naraysa** [ahaliassos/raven#4]
Thanks for sharing the model checkpoints.

However, there is an issue when loading the base model pretrained on LRS3 and VoxCeleb, finetuned on LRS3: vsr_prelrs3vox2_base_ftlrs3.pth

torch.load('ckpts/vsr_prelrs3vox2_base_ftlrs3.pth')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/home/anaconda3/envs/pyt/lib/python3.8/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/project/home/anaconda3/envs/pyt/lib/python3.8/site-packages/torch/serialization.py", line 1018, in _legacy_load
    return legacy_load(f)
  File "/project/home/anaconda3/envs/pyt/lib/python3.8/site-packages/torch/serialization.py", line 904, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/project/home/anaconda3/envs/pyt/lib/python3.8/tarfile.py", line 2060, in extract
    tarinfo = self.getmember(member)
  File "/project/home/anaconda3/envs/pyt/lib/python3.8/tarfile.py", line 1782, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

Could you kindly share the correct model weights.

**Comment by ahaliassos** [comment]
Thanks for pointing this out! 

I uploaded it again - hopefully it works now :)

**Comment by naraysa** [comment]
Thank you. It does load now.
